I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 82, in script call
    call expression _return
  File "game/script.rpy", line 82, in script call
    call expression _return
ScriptError: could not find label 'caso_2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 82, in script call
    call expression _return
  File "C:\Program Files (x86)\RenPy\renpy-6.99.7-sdk\renpy\ast.py", line 1306, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 82, in script call
    call expression _return
  File "C:\Program Files (x86)\RenPy\renpy-6.99.7-sdk\renpy\script.py", line 843, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'caso_2'.

Windows-8-6.2.9200
Ren'Py 6.99.7.858
GamePolitica 0.0
